Barra = [
    "Quem? Te perguntou!",
    "Conheci a gi? A gigantesca vontade que eu tenho de te ignorar!",
    "A conversa ja chegou ao esgoto"
    ]
Curiosidade = [
    "As 3 famílias mais ricas do mundo possuem uma fortuna superior à soma das riquezas dos 48 países mais pobres do mundo.",
    "Os homens possuem 6 vezes mais chances de serem atingidos por relâmpagos, visto que tendem a ignorar sinais de perigo com mais frequência que as mulheres.",
    "EUA, Birmânia e Libéria foram os únicos países a não tomar o sistema métrico como padrão para medidas.",
    "Aproximadamente 2500 pessoas canhotas morrem por ano, na tentativa de utilizar equipamentos e ferramentas para pessoas destras.",
    "É proibido vender uma casa assombrada em Nova York, sem avisar o comprador.",
    "Fredric John Baur foi o responsável pela invenção das batatas Pringles. No ano de 2008, quando morreu, suas cinzas foram armazenadas em uma embalagem dessas batatas.",
    "O morango possui mais vitamina C do que a laranja!",
    "Em uma sala com 23 pessoas, existem chances de 50% de duas delas possuírem a mesma data de aniversário.",
    "O Mestre Yoda, de Star Wars, foi projetado para se parecer com Albert Einstein.",
    "O cheiro de um humano pode ser detectado por cães a mais de 1 quilômetro de distância",
    "Mais de 1.000.000 de euros são jogados na ‘Fontana de Trevi’ (Itália). De tempos em tempos a prefeitura de Roma recolhe as moedas e doa para a caridade.",
    "O único planeta do Sistema Solar que não tem nome de um deus, é o nosso.",
    "Em 1033, foi registrada uma impressionante temperatura. Afinal, não é todo dia que os termômetros batem os 136ºC.",
    "Alguns pesquisadores acreditam que a Terra tinha duas luas. A segunda, contudo, teria colidido com a que conhecemos hoje. Portanto, acabou sendo destruída.",
    "A Terra abriga vida por, aproximadamente, mais de 80% de sua existência.",
    "Se todas as pessoas do mundo vivessem como um habitante médio dos Estados Unidos, seria preciso recursos de 4,5 planetas como o nosso.",
    "O ano de 1816 é conhecido como o “ano sem verão”. A propósito, diversos fenômenos que aconteceram na Terra, incluindo erupções vulcânicas, influenciaram este acontecimento. Por exemplo, a temperatura do planeta baixou tanto que, como resultado, não houve verão.",
    "Em 1923, um tornado de fogo levou 38 mil pessoas à morte, em Tókio.",
    "A Ilha de Socotra é tão isolada que, por lá vivem espécies que não são encontradas em nenhum outro lugar do planeta. Não à toa, portanto, ficou conhecida como “o lugar mais estranho da Terra”.",
    "Muito antes das árvores, a Terra era coberta por cogumelos gigantes.",
    "De toda a vida animal que se desenvolveu no planeta, aproximadamente 80% têm 6 ou mais pernas.",
    "O thaumoctopus mimicus é um polvo capaz de mudar sua cor e imitar a de outros seres marinhos. Em suma, até hoje, são conhecidas 15 cores que ele pode imitar.",
    "Um beija-flor, afinal, pode pesar menos que uma moeda de um centavo.",
    "Se um leão macho se torna o líder do grupo, ele mata todos os filhotes do líder anterior.",
    "A língua das girafas pode chegar a medir 50 cm. Sobretudo, elas também as usam para limpar suas orelhas.",
    "O corpo de uma água-viva é composto de 95% de água.",
    "Cães de pradaria se cumprimentam com beijos.",
    "As vacas são capazes de definir suas melhores amigas e sofrem com as perdas.",
    "A pele de uma rã dourada venenosa possui toxinas suficientes para matar 100 pessoas.",
    "Ao contrário da crença popular, a cor vermelha não atiça os touros.",
    "Os únicos mamíferos capazes de voar são os morcegos.",
    "Humanos e coalas possuem as digitais muito parecidas.",
    "Uma formiga pode carregar até 60 vezes o seu peso.",
    "Uma cobra píton grande é capaz de engolir uma cabra inteira.",
    "Em suma, 10% dos ossos de um gato estão presentes em sua cauda.",
    "Basicamente, um crocodilo do Nilo pode prender a respiração por até 2 horas.",
    "Águas-vivas não possuem cérebro. Aliás, não têm também coração ou ossos. Para se movimentarem, portanto, usam os sensores nervosos presentes em seus tentáculos.",
    "Existem mais formas de vida vivendo na sua pele do que humanos habitando a Terra.",
    "Em média, cada pessoa perde 4kg de pele morta em um ano",
    "Charles Osborne teve uma crise de soluços que durou, nada mais nada menos que, 69 anos. Começou em 1922, quando pesava um cerdo para sacrificá-lo e só parou quando ele já tinha 97 anos.",
    "Todas as pessoas que têm olhos azuis têm um mesmo ancestral em comum.",
    ]